destination: ./_site
server: true
auto:        true
lsi:         false
server_port: 4000
permalink:   date
markdown: kramdown 
pygments: true

kramdown:
  input:  GFM
rdiscount:
  extensions: 
      - smart
